app/src/main/AndroidManifest.xml, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/ReportFragment.java, app/src/main/res/layout/report.xml
A small work for the issue #11
=> Landscape mode

app/src/main/AndroidManifest.xml
=> Disable db backup

app/src/main/res/values-ar/strings.xml
i18n : Updating arabic translation : 100% translated.
=> i18n : Updating arabic translation

app/src/main/res/drawable/square_purple.xml, app/src/main/res/layout/report.xml
Changed the report.xml so it looks nicer:
- Added rounded corners to the purple titles
- Changed the two numbers, so they match the style in the app list
- Improved the app title and icon margins and padding
- Added margins and padding to various other objects
=> More beautiful UI: report.xml

app/src/main/res/values-pt-rBR/strings.xml
=> Brazilian Portuguese translation

README.md
Should be pretty self-explanatory :smile_cat:
=> docs: Add GitHub actions & LGTM badges to README

app/build.gradle, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/CheckAppActivity.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/ApplicationViewModel.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/ComputeAppList.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/MyTrackersFragment.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/TrackerFragment.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/NetworkManager.java, build.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle
This pull request aims to:
- Upstream Gradle and libraries to the latest stable upstream version
- Upstream deprecated code as much as possible
Commit messages are self-explanatory on what changes have been made.
=> exodus-android-app: Upstream gradle, libraries and code

app/build.gradle
Update version code
Update version name
=> release 2.2.0

fastlane/metadata/android/en-US/changelogs/10.txt, fastlane/metadata/android/fr-FR/changelogs/10.txt
=> Add changelog for next release

app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle
Change `minifyEnabled` to `true`
Change `minimunSdkCompile`
Upgrade gradle version
=> Optimize apk

.github/workflows/main.yml
Add paths-ignore to execute WKF only when you change code about app
=> Add paths-ignore in Github actions

fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/en-US/short_description.txt, fastlane/metadata/android/fr-FR/changelogs/9.txt, fastlane/metadata/android/fr-FR/full_description.txt, fastlane/metadata/android/fr-FR/short_description.txt
- Update full and short description on Fdroid metadata (en-US/fr-FR) with description on Play Store
-  Fix space
=> Update description in Fdroid metadata

.github/workflows/main.yml, .github/workflows/release.yml, app/build.gradle
This PR:
- Update debug workflow
- Add release workflow
I wait you add keystore and API KEY on Github secrets to doing changes.
After we submit 3.0 version on Play Store, i update release workflow to create release on Github (with APK and changelog).
=> Update Github actions

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/subfrags/ADTrackersFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/model/AppsRVAdapter.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/objects/VersionReport.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/CommonExtensions.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
To add feature https://github.com/Exodus-Privacy/exodus-android-app/discussions/154#discussioncomment-2565753
=> app: add toast on version chips #154

.github/workflows/main.yml, .github/workflows/release.yml
Update debug workflow
- Update triggers to start workflow foreach pull request
- Remove tags triggers 
Update release workflow
- Fix workflow
- Add action to create release
- Add action to add apk on release Github
=> Improve workflows

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/dialog/ThemeDialogFragment.kt, app/src/main/res/menu/about_menu.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
- Add menu on AboutFragment
- Add new ThemeDialog Fragment
I have add new dialog with ExodusDialogFragment like model.
I have just create dialog, i don't have develop code behind dialog to switch between theme
=> Add new Dialog Fragment to select Theme

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/network/NetworkManager.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/NotificationManagerModule.kt, app/src/main/res/layout/fragment_about.xml
Compat classes and methods to manage device in API 21
- NotificationManagerCompat
- registerNetworkCallback
`@android:id/list_container` is a false positive (bug in the lib source code) but no problem with it.
=> fix: minSDK 21 - aa0da6ce27b2b142a1e3f21fc657972dbd321285

app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
La relecture a été faite sans prendre en compte l'impact sur l'apparence de l'application (longueur des phrases etc), si certains des changements faits pour prioritiser la compréhension et le sens nuisent à la fonctionnalité on peut les retravailler ou les annuler.
=> Relecture des versions anglaise et française

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/CommonExtensions.kt
=> Fix apps with version code 0 always being shown as analyzed

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt, app/src/main/res/layout/fragment_apps.xml
Added enhancement as requested in issue #241 
https://github.com/Exodus-Privacy/exodus-android-app/assets/112970189/a80835c1-1fef-4ef3-b322-6624d7e2b3c1
=> Added FAB to update reports

.github/workflows/main.yml, .github/workflows/release.yml
- Bump setup-java to [v4](https://github.com/actions/setup-java/releases/tag/v4.0.0)
- Bump exodus-standalone to v1.4.0
=> Bump Github Actions

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersFragment.kt, app/src/main/res/layout/fragment_tracker_detail.xml
Fixes #50
Closes #345
|Before|After|
|-|-|
|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/ac5e2633-c7b1-448b-a2d0-f1d11c7a4e6d" height=500 />|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/77fd814c-653f-4e21-9bda-ba821d1ee6bc" height=500 />|
=> Add trackers number in tracker list fragment

app/build.gradle.kts, fastlane/metadata/android/en-US/changelogs/19.txt, fastlane/metadata/android/fr-FR/changelogs/19.txt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
In the last version, I updated logic to get API_KEY and I broke logic in yml file in F-Droid repository :(
This PR:
- rollback changes
- Bump dependencies
- Bump version and add changelog
=> Fix connection to server not working

app/src/main/res/layout/fragment_tracker_detail.xml
Fixes #191
Before
https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/e868b0b6-dd36-4d7d-aef5-52403ccb4d04
After
https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/eda12653-f3b0-413e-8a11-ecac26a57fa0
=> Fix wrong focus on app recycler view in tracker detail fragment

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt
- Add getLocaleWebsiteURL method to return right url following if language of device is en or fr and add end of privacy policy url
=> Add support for french privacy policy

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/model/TrackersRVAdapter.kt, app/src/main/res/layout/recycler_view_tracker_item.xml
#409 
- Replaced with constraint layout
- Replaced getDisplayWidth with holder.itemView.width
- Applied post method
=> Replace relative layout with constraint layout

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/Navigation.kt, app/src/main/res/anim/fast_out_extra_slow_in.xml, app/src/main/res/anim/fragment_enter.xml, app/src/main/res/anim/fragment_exit.xml, app/src/main/res/anim/fragment_pop_enter.xml, app/src/main/res/anim/fragment_pop_exit.xml, app/src/main/res/anim/slide_in_bottom.xml, app/src/main/res/anim/slide_in_left.xml, app/src/main/res/anim/slide_in_right.xml, app/src/main/res/anim/slide_in_top.xml, app/src/main/res/anim/slide_out_left.xml, app/src/main/res/anim/slide_out_right.xml
Before
https://github.com/Exodus-Privacy/exodus-android-app/assets/58552395/aac2ced7-aaf7-4088-8692-0c4587b1cb37
After
https://github.com/Exodus-Privacy/exodus-android-app/assets/58552395/98fd53f0-3faf-4a7e-9e0e-075727de65ba
Closes #346
=> Improve transitions & add animation to hide bottom bar

app/build.gradle.kts, gradle/libs.versions.toml
It's seems somes dependencies are unused in app. Remove from config can save some Kb on app size
=> Drop unused dependencies
