gradle/wrapper/gradle-wrapper.properties
This patch forces Gradle to verify the downloaded `gradle-4.1-all.zip` file.
=> Add a SHA-256 sum for the downloaded Gradle

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/PermissionListAdapter.java, app/src/main/res/layout/permission_item.xml
Some permissions have no descriptions. So, instead of putting a "▶" char that opens a blank content, the click is no longer handled and the char is replaced by "■" to show there is no content.
=> Expand buttons

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/ApplicationListAdapter.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
A proposition to improve the message.
Instead of:
> There\'s no report for the installed version, the information displayed is based on another (presumably older) version
it says (for example):
> There's no report for the installed version (1.2.0), the information displayed is based on another (1.0.0) version
When the version code is not available, it uses the version number.
DO NOT MERGE YET: The Arabic translation **IS NOT correct** (if someone could help with that...)
=> [WIP] Better message when version doesn't match

app/src/main/res/layout/app_item.xml
Hi,
Here is a microscopic PR to fix a margin issue. Application icons were colliding with the cells separators :)
=> fix: add margins in application cell

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/ApplicationListAdapter.java
I noticed that scrolling in the application list wasn't smooth so I worked on some improvements.
- multiple access to the database is done each time a cell is rendered in the `onBindViewHolder()` method. I fixed that by extracting all the values needed to be displayed into a `ViewModel` class
- computation to check whether or not a cell is visible is done in the `getItemViewType()` method. I fixed that by computing the visibility right after a search.
Working with a ViewModel class allows features such as #45 and #22 to be implemented easily.
Cheers
🌮
=> feat(applications): improve recyclerview scrolling

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/ApplicationListAdapter.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/ApplicationViewModel.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/AppListFragment.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/ComputeAppListTask.java
Creating a complete viewmodel list as done in #54 speeds up scrolling but slows down the first RecyclerView display a bit. It is noticeable when the application starts and when navigating back from app detail. It is mainly due to the filtering of apps not coming from play store and also the database access to fetch reports and trackers being done on the main thread.
In this PR I did the following changes
- extracted the ViewModel list creation in a task running on a separate thread
- re-displayed the last computed list when navigating back from detail to homescreen
Now main screen is ready to handle filtering and sorting apps !
Cheers
🌮
=>  feat: speed up application start and back navigation 

app/build.gradle, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.java, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/AboutFragment.java, app/src/main/res/drawable/ic_information.xml, app/src/main/res/layout/fragment_about.xml, app/src/main/res/menu/bottom_nav_menu.xml, app/src/main/res/values/strings.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
This MR:
- Upstreams the Gradle and dependencies to the latest stable release
- Adds a new About Fragment which displays app logo, description, and privacy policy URL (not hosted on the server yet)
This should close https://github.com/Exodus-Privacy/exodus-android-app/issues/111, however, keep in mind that the URL seems not hosted or public yet and should be handled as well.
The URL can be changed by maintainers by editing the variable value in `app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/AboutFragment.java`
=> Introduce About Fragment

app/src/main/AndroidManifest.xml
Add QUERY_ALL_PACKAGES permission in `AndroidManifest` file (see https://support.google.com/googleplay/android-developer/answer/10158779?hl=en#zippy=%2Cpermitted-uses-of-the-query-all-packages-permission%2Cexceptions%2Cinvalid-uses).
=> Add QUERY_ALL_PACKAGES permission

.github/workflows/main.yml
Fixes #134 
Adds a new step to GitHub Actions to scan the generated apk with [exodus-standalone](https://github.com/Exodus-Privacy/exodus-standalone)
=> ci: Scan with exodus-standalone 

fastlane/metadata/android/en-US/changelogs/10.txt, fastlane/metadata/android/en-US/changelogs/11.txt, fastlane/metadata/android/en-US/changelogs/12.txt, fastlane/metadata/android/fr-FR/changelogs/10.txt, fastlane/metadata/android/fr-FR/changelogs/11.txt, fastlane/metadata/android/fr-FR/changelogs/12.txt
- With release 2.2.0, i have doing error in name on latest changelogs en/fr.
- Because for release 2.1.1, we have not changelog. (changelog is not necessary, this release was created to fix bugs).
=> Fix name file for latest changelogs

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivityViewModel.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/network/NetworkManager.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/NotificationManagerModule.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
- The network connection is made by observers that are attached to the viewModel of the activity and directly in the service.
- The coroutines are changed to cancel the job when necessary and when the service is closed.
- I also moved the Toast for the data fetch to put it in the service. The code is called only once and is only run if the service performs the action.
I tried to adapt to the style by using Dagger but I used an anonymous function for the observers. Let me know if it's ok for you.
=> fix: add no internet Snackbar and fix crash #178

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/model/ADPermissionsRVAdapter.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/PackageManagerModule.kt
- Fix regex to show all permissions and description
- Sort permissions by name
- Hide expand button if description about permission is null
- If permission doesn't have label or description we show permission after regex like title and full permission like subtitle
=> Show all permissions on ADPermissionsFragment

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt, app/src/main/res/layout/fragment_app_detail.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Some app have same versionName (app.versionName = report.versionName) on AppDetailFragment but versionCode is different.
To explain why Exodus say report mismatch with app installed.
- I have add new text `Same app version may be different following Android version and device used.` only if report mismatch and report.versionName is equal app.versionName
=> app: Add new text when 2 versionName is same on AppDetailFragment

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/app/ExodusApplicationDao.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/tracker/TrackerDataDao.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/PackageManagerModule.kt
Improved default sorting with remove case sensitive on:
- apps name 
- trackers name 
- permissions name
@J-Jamet I don't have find how sorting correctly when apps  name have accents.
Tested on :
- Pixel 6 - Android 12 ✅
- Honor 8 - Android 8 ✅
- Pixel 5 - Android 5 (Emulator) ✅
=> Improved apps, trackers and permissions sorting

.github/workflows/release.yml, app/build.gradle
Origin of the problem is type of one variable is incorrect in Exodus Service.
When gradle use optimizations to reduce size app. App doesn't work. She never download trackers and reports.
Remove there optimizations is temporarily.
The correction is already tested.
=> Reports and trackers are never download

app/src/main/res/layout/fragment_a_d_permissions.xml, app/src/main/res/layout/fragment_a_d_trackers.xml
| Before | After |
|---|---|
|<img src="https://user-images.githubusercontent.com/87148630/202028374-ea81b5c9-a6c5-4606-9632-3b3bb0da8370.png" height=400 /> | <img src="https://user-images.githubusercontent.com/87148630/202028210-74595b3c-5a29-456a-96bc-06a4ac93038c.png" height=400 /> |
| <img src="https://user-images.githubusercontent.com/87148630/202028610-60efead3-989e-45bf-9ff1-76a32536c553.png" height=400 /> | <img src="https://user-images.githubusercontent.com/87148630/202028710-856742dc-581f-43da-bb62-8b1f54cbb551.png" height=400 />
@jfoucry have ask to increase spacing in permissions and trackers tab.
If it's not enough, i can increase again :)
=> Improve spacing between text in permissions sub fragment and trackers sub fragment

fastlane/metadata/android/en-US/short_description.txt, fastlane/metadata/android/fr-FR/short_description.txt
- Reduce `fr-FR` and `en-US` short description size according to [F-Droid informations](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/).
Fix #204
=> Reduce short description size

.github/workflows/main.yml, .github/workflows/release.yml
network_security_config.xml is only use, to execute integration tests in local
Keep this file can broke access to Internet, remove file is more safe to be sure app can get reports and trackers from Exodus server
(Need to do same thing on fdroid metadata file)
=> Remove network config in Github Actions

.github/workflows/main.yml, .github/workflows/release.yml
Bump to 17 in main and release.
=> Bump JDK version

app/src/androidTest/java/org/eu/exodus_privacy/exodusprivacy/ExodusPackageRepositoryTest.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/packageinfo/ExodusPackageRepository.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/CommonExtensions.kt
This is targeting the deprecations introduced with the update to API 33.
* Create extension functions taking care to call the appropriate PackageManager method
* Update tests accordingly
* Little bit of test clean up
=> Fix deprecations

app/src/main/res/layout-land/fragment_about.xml
=> [Fix] About section landscape mode

.github/workflows/main.yml, .github/workflows/release.yml
Bump setup-java to v3 because, v1 use Node.js 12 (this version is deprecated).
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Bump setup-java to v3

app/src/androidTest/java/org/eu/exodus_privacy/exodusprivacy/ExodusTestRunner.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/dialog/ExodusDialogFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/model/TrackersRVAdapter.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/network/NetworkManager.kt
This PR update syntax.
Actually, we used old version of ktlint because we do not respect new rules (Package name must not contain underscore)
But i have update ktlint on my personnal repository to use latest version linter (0.50) and fix syntax.
=> Update syntax to latest ktlint version

app/build.gradle.kts, app/schemas/org.eu.exodus_privacy.exodusprivacy.manager.database.ExodusDatabase/2.json, app/src/androidTest/java/org/eu/exodus_privacy/exodusprivacy/ExodusDatabaseRepositoryTest.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/ExodusDatabase.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/ExodusDatabaseConverters.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/ExodusDatabaseModule.kt, build.gradle.kts, gradle/libs.versions.toml
#322 
- Added the version and lib in lib.versions.toml
- Replaced kapt with ksp
- Replaced javaCompileOptions with ksp
- Added type converter for MutableList<String>
- Passed an instance of the type converters class to the Room Database Builder
=> fixed issue: migrate to ksp annotation processor

.github/workflows/main.yml, .github/workflows/release.yml
With this new version, the size of artifact visible in checks takes now size of archive instead take a size of elements inside archive
=> Bump upload artifact actions to v4

app/build.gradle.kts, gradle.properties
buildConfig in gradle.properties is deprecated in latest version of gradle (8.4), we need to specify property in each module of the project -> https://stackoverflow.com/questions/74634321/fixing-the-build-type-contains-custom-buildconfig-fields-but-the-feature-is-di
I have also removed unused value -> I have check that doesn't break Fdroid build
=> Move build config property

.editorconfig, app/build.gradle.kts
This PR updates linter to the latest version (1.1.1), this version doing break changes that's why I have disabled rules to do not need to reformat all files and pollutes git blame.
List of rules:
https://pinterest.github.io/ktlint/latest/rules/experimental/
=> Use latest version of ktlint

app/src/main/AndroidManifest.xml, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/subfrags/ADPermissionsFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/subfrags/ADTrackersFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/BrowserUtils.kt
Fixes #286
This PR fix crashes on devices with browser doesn't support custom tab.
- Add new `openURL` method to know if default browser supports custom tabs -> more information here https://developer.chrome.com/docs/android/custom-tabs/howto-custom-tab-check
- Add new `startActivity` method to don't generate crash when devices doesn't have browser, app mail or app store.
=> Fix crash on devices without browsers support custom tabs

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/CommonExtensions.kt
This PR implements a new util method to copy content in the clipboard, this new method is used in tracker detail fragment to add the ability to copy network signatures (with long press) in clipboard to use in ad blocker app
Fixes #89
https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/340d0608-c24e-4fcf-8dbf-7f22bea4590a
=> Add ability to copy network signature

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt
This avoids the unnecessary redirect via mastodon.social and this ugly screen:
=> change mastodon url to direct framapiaf.org link

app/build.gradle.kts
Without this the build fails with `KSP apoption does not match \S+=\S+: room.schemaLocation=C:\Users\Conny Duck\AndroidApps\exodus-android-app\app\schemas`
=> fix building on Windows with spaces in path

app/src/main/res/layout/fragment_app_detail.xml
I have replaced purple color by transparent color when user select a tab to switch to permissions tab or trackers tab.
|Before|After|
|-|-|
|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/f643252b-cb6e-4a7b-8dea-e02b31e60f2f" height=500 />|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/8e88308f-41b6-431d-a2b3-170aeb2d2e61" height=500 />
=> Remove pressed color when you switch between tabs in app detail fragment

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt, app/src/main/res/layout/fragment_tracker_detail.xml
This PR fixes:
- Scrolling not working properly -> introduced by #398
- Fix number of apps present in the list -> introduced by #309 (In latest version, we can see at the maximum, 8 apps in list)
Before
https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/42f29c01-7f9a-469a-bfda-f047caf4e7ad
After
https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/39520b11-cf0a-463f-9a54-4b5833a5dc72
=> Fix tracker detail fragment layout

.editorconfig, app/build.gradle.kts
https://github.com/pinterest/ktlint/releases/tag/1.2.1
I have disabled backing-property-naming rule to allow to name variables with an underscore as the first character -> Google uses this syntax in the documentation
https://pinterest.github.io/ktlint/latest/rules/standard/#property-naming
=> Bump ktlint to 1.2.1 version

app/src/main/res/layout/recycler_view_app_item.xml, app/src/main/res/values/strings.xml
=> Fixed spelling error

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/model/ADStatusRVAdapter.kt, app/src/main/res/layout/recycler_view_ad_status_item.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR adds a new text when an app doesn't have reports on exodus to explain the potential reasons why cannot be analyzed by exodus.
|Before|After|
|-|-|
|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/c736b8eb-8d47-4ab5-ae3c-4addd1203030" height=500 />|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/3cbccd90-af02-44ce-abea-5bd049d57997" height=500/>|
=> Add text about restrictions

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsViewModel.kt
=> Fix shimmer effect showing behind apps on blank search query

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt
=> Fix bottom nav showing up in app-reports on orientation changes

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/IntentUtils.kt
This PR:
- Rename `BrowserUtils` to `IntentUtils` class
- Remove `startWebActivity` function
- Add `startIntent` function to open Intent (URL, Intent to settings, mail adress)
- Replaces `startActivity` with `startIntent`  in all classes
=> Add new Intent utils class

README.md, app/build.gradle.kts, fastlane/metadata/android/en-US/changelogs/22.txt, fastlane/metadata/android/fr-FR/changelogs/22.txt
Fixes #435
This PR:
- Remove support of Android 5 and Android 5.1
- Bump app version
- Add changelogs
- Update readme to explain to the user that old versions continue to work on Android 5
[Build test release](https://github.com/Exodus-Privacy/exodus-android-app/actions/runs/9145419659)
With this new version, we save 0,1Mb
=> Remove support of Android 5

app/src/main/res/layout-land/fragment_about.xml, app/src/main/res/layout-sw600dp-land/fragment_about.xml
When the user uses a big police name of the app is cut on About screen.
|Before|After|
|-|-|
|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/e4fec48f-cae5-4fba-b899-00d1ffb7b4fb" height=150 />|<img src="https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/0747fee1-b505-4517-bad4-01072741ca2e" height=150 />|
=> Fix name app in About Fragment

.github/workflows/main.yml, README.md, doc/RELEASE.md
- Update readme
- Add release documentation
- Remove trigger workflow when user pushes change in doc directory
=> Improve documentations

README.md
I have discovered recently [Obtainium](https://github.com/ImranR98/Obtainium), this app adds the ability to update your apps by listening to new versions in Github.
It's very easy to use and used by a lot of open-source projects.
I suggest adding a badge in readme
[Exodus report](https://reports.exodus-privacy.eu.org/fr/reports/449542/)
Todo
=> Add Obtainium badge

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/IntentUtils.kt
This PR fixes Android Studio warning because we init a variable with a null intent. I have replace null init with lateinit to tell to the compiler that variable is init later and adds the type of variable.
=> Fix warning

app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersFragment.kt, app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/ScreenUtils.kt
This PR:
- Create a new Screen util class
- Create a new function `getColumnScreen` to get the size of the screen and return the number of columns used in UI (used on tablet to have two columns and use all space of screen)
- Use new function in all classes
=> Add new screen utils class
